### ISSUE TITLE
Server rejects placing 8 on 8

### ISSUE THREAD

**Issue by Guldvar** [Paladinking/NodeCardGame#1]
Placing an 8 on an 8 gives 'Not a valid 8 play'
![image](https://user-images.githubusercontent.com/15779987/193074311-d3652775-8035-4494-9087-725631233635.png)

**Comment by Paladinking** [comment]
Löst , https://github.com/Paladinking/NodeCardGame/commit/7aba101f5bebf981b54b8dd535e8f30a13792f19
